gweriojnger

diff --git a/.github/workflows/checker.yaml b/.github/workflows/checker.yaml
--- a/.github/workflows/checker.yaml
+++ b/.github/workflows/checker.yaml
@@ -18,17 +18,26 @@ jobs:
             - name: Run Main.go
               run: |
                 output=$(go run main.go)
-                echo "$output"
-                if echo "$output" | grep -q "No Dantotsu artifact found"; then
-                  release_info=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                      "https://api.github.com/repos/${{ github.repository }}/releases/latest")
-                  release_name=$(echo $release_info | jq -r '.name')
-                  echo "workflow_title=$release_name" >> $GITHUB_ENV
-                else
-                  workflow_title=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                      "${{ env.dantotsu_runs }}" | jq -r '.workflow_runs[0].display_title')
-                  echo "workflow_title=$workflow_title" >> $GITHUB_ENV
-                fi
+                last_message=$(echo "$output" | tail -n 1)
+                echo "$last_message"
+                workflow_title=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+                    "${{ env.dantotsu_runs }}" | jq -r '.workflow_runs[0].display_title')
+                echo "workflow_title=$workflow_title" >> $GITHUB_ENV
+
+              #   - name: Run Main.go
+              # run: |
+              #   output=$(go run main.go)
+              #   echo "$output"
+              #   if echo "$output" | grep -q "No Dantotsu artifact found"; then
+              #     release_info=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              #         "https://api.github.com/repos/${{ github.repository }}/releases/latest")
+              #     release_name=$(echo $release_info | jq -r '.name')
+              #     echo "workflow_title=$release_name" >> $GITHUB_ENV
+              #   else
+              #     workflow_title=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              #         "${{ env.dantotsu_runs }}" | jq -r '.workflow_runs[0].display_title')
+              #     echo "workflow_title=$workflow_title" >> $GITHUB_ENV
+              #   fi
 
             - name: Get Apk Info
               id: apk-info
@@ -56,18 +65,18 @@ jobs:
                   tag_name: ${{ steps.apk-info.outputs.version-name }}
                   name: ${{ env.workflow_title }}
 
-    rerun-workflow:
-        name: Re-run workflow
-        needs: check_for_update
-        if: success() || failure()
-        runs-on: ubuntu-latest
-        steps:
-            - name: Sleep until 5 minutes have passed
-              run: |
-                  sleep 300
+    # rerun-workflow:
+    #     name: Re-run workflow
+    #     needs: check_for_update
+    #     if: success() || failure()
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Sleep until 5 minutes have passed
+    #           run: |
+    #               sleep 300
 
-            - name: Re-trigger workflow
-              run: gh workflow run checker.yaml
-              env:
-                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-                  GH_REPO: ${{ github.repository }}
+    #         - name: Re-trigger workflow
+    #           run: gh workflow run checker.yaml
+    #           env:
+    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #               GH_REPO: ${{ github.repository }}
